// Standalone copy of the initial catalog for the /api/admin/seed bootstrap
// endpoint. Deliberately does NOT import from src/data/mockData.ts — that
// file imports .jpg assets directly (a Vite-only feature that resolves them
// to build-time URLs), which crashes Node's plain ESM loader when the file
// is pulled into a serverless function outside the Vite build pipeline
// (ERR_UNKNOWN_FILE_EXTENSION). Uses stable hosted image URLs instead.

const FLOWER_1 = 'https://images.unsplash.com/photo-1561181286-d3fee7d55364?auto=format&fit=crop&w=800&q=80';
const FLOWER_2 = 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80';
const PERFUME_1 = 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=800&q=80';
const CHOCOLATE_1 = 'https://images.unsplash.com/photo-1548848221-0c2e497ed557?auto=format&fit=crop&w=800&q=80';

export const SEED_PRODUCTS = [
  {
    id: 'abaq-royal-red',
    nameAr: 'باقة عبق الملكية - البرغندي والذهب',
    nameEn: 'Abaq Royal Burgundy & Gold Bouquet',
    descriptionAr: 'باقة فاخرة تضم 50 وردة جوري هولندية باللون البرغندي الداكن مع لمسات الذهبي وتغليف حريري فاخر وشريط مطرز باسم عبق نزوى.',
    descriptionEn: 'Luxury bouquet of 50 Dutch burgundy roses with gold leaf accents, silk wrapping and embroidered Abaq Nizwa ribbon.',
    price: 45.00,
    originalPrice: 55.00,
    category: 'bouquets',
    occasionId: 'wedding',
    images: [FLOWER_1, FLOWER_2],
    isBestSeller: true,
    isFeatured: true,
    flowerCountOptions: [25, 50, 75, 100],
    wrappingColors: [
      { nameAr: 'برغندي عبق', nameEn: 'Abaq Burgundy', hex: '#7D0A0A' },
      { nameAr: 'أبيض لؤلؤي', nameEn: 'Pearl White', hex: '#FFFFFF' },
      { nameAr: 'ذهبي مطفأ', nameEn: 'Matte Gold', hex: '#D4AF37' },
      { nameAr: 'وردي ناعم', nameEn: 'Soft Pink', hex: '#FCECEF' },
    ],
    sizes: [
      { nameAr: 'قياسي (50 وردة)', nameEn: 'Standard (50 roses)', priceMultiplier: 1.0 },
      { nameAr: 'كبير (75 وردة)', nameEn: 'Large (75 roses)', priceMultiplier: 1.4 },
      { nameAr: 'ملكي (100 وردة)', nameEn: 'Royal (100 roses)', priceMultiplier: 1.8 },
    ],
    inStock: true,
    stockQuantity: 15,
    tagsAr: ['الأكثر مبيعاً', 'ورد جوري', 'برغندي', 'زفاف'],
    tagsEn: ['Best Seller', 'Dutch Roses', 'Burgundy', 'Wedding'],
  },
  {
    id: 'nizwa-frankincense-perfume',
    nameAr: 'عطر عبق نزوى - اللبان والعنبر الملكي (100ml)',
    nameEn: 'Abaq Nizwa Royal Amber & Frankincense (100ml)',
    descriptionAr: 'عطر نيش نفاذ مستوحى من تاريخ نزوى العريق، يمزج أجود أنواع اللبان العماني مع العنبر الفاخر والورد الطائفي.',
    descriptionEn: 'Niche luxury perfume inspired by Nizwa heritage, blending rare Omani Royal Frankincense, amber, and Taif rose.',
    price: 68.00,
    originalPrice: 78.00,
    category: 'perfumes',
    occasionId: 'thank-you',
    images: [PERFUME_1],
    isBestSeller: true,
    isFeatured: true,
    inStock: true,
    stockQuantity: 20,
    tagsAr: ['عطور نيش', 'لبان عماني', 'فاخر', 'رجالي ونسائي'],
    tagsEn: ['Niche Perfume', 'Omani Frankincense', 'Unisex', 'Luxury'],
  },
  {
    id: 'gold-truffles-box',
    nameAr: 'صندوق شوكولاتة عبق نزوى المذهبة (36 قطعة)',
    nameEn: 'Abaq Nizwa Gold Leaf Truffles Box (36 pcs)',
    descriptionAr: 'صندوق خشبي محفور يدوياً محشو بشوكولاتة بلجيكية فاخرة بنكهات الهيل، الفستق، والكراميل المملح ومغلفة بذهب عيار 24 قابل للأكل.',
    descriptionEn: 'Hand-carved wooden box filled with 36 artisan Belgian truffles with Cardamom, Pistachio & Salted Caramel dusted with 24k edible gold.',
    price: 32.00,
    originalPrice: 38.00,
    category: 'chocolates',
    occasionId: 'engagement',
    images: [CHOCOLATE_1],
    isBestSeller: true,
    isFeatured: true,
    inStock: true,
    stockQuantity: 25,
    tagsAr: ['شوكولاتة بلجيكية', 'ذهب عيار 24', 'هدايا راقية'],
    tagsEn: ['Belgian Chocolate', 'Edible Gold', 'Luxury Gifts'],
  },
  {
    id: 'wedding-mahr-tray',
    nameAr: 'صينية المهر الملكية - كـريستال ورد وبرغندي',
    nameEn: 'Royal Mahr Crystal Tray & Flower Setup',
    descriptionAr: 'صينية اكرليك فاخرة مقطوعة بالليزر بحواف ذهبية وتنسيق ورد دوار شمس وأوركيد أبيض مع مكان مخصص للذهب والمهر.',
    descriptionEn: 'Laser-cut acrylic luxury Mahr tray with gold accents, natural orchids & white roses tailored for wedding presentations.',
    price: 120.00,
    originalPrice: 145.00,
    category: 'wedding',
    occasionId: 'wedding',
    images: [FLOWER_2, FLOWER_1],
    isBestSeller: false,
    isFeatured: true,
    inStock: true,
    stockQuantity: 5,
    tagsAr: ['تجهيز زواج', 'صينية مهر', 'تجهيز عرايس'],
    tagsEn: ['Wedding Tray', 'Bridal Mahr', 'Custom Setup'],
  },
  {
    id: 'grad-rose-box',
    nameAr: 'صندوق التخرج الملكي - ورد وشوكولاتة وعطر',
    nameEn: 'Royal Graduation Victory Gift Box',
    descriptionAr: 'صندوق جلد برغندي فاخر يحتوي على 30 وردة جورية، شوكولاتة التخرج المكتوب عليها مبروك التخرج، وقارورة عطر عبق 30ml.',
    descriptionEn: 'Burgundy leather box with 30 fresh roses, congratulations chocolates, and a 30ml Abaq signature perfume bottle.',
    price: 58.00,
    originalPrice: 65.00,
    category: 'graduation',
    occasionId: 'graduation',
    images: [CHOCOLATE_1, PERFUME_1],
    isBestSeller: true,
    isNew: true,
    inStock: true,
    stockQuantity: 18,
    tagsAr: ['تخرج', 'هدايا تخرج', 'صندوق مبروك'],
    tagsEn: ['Graduation', 'Victory Box', 'Roses & Perfume'],
  },
  {
    id: 'white-lily-vase',
    nameAr: 'فازة الزنبق الملكي الأبيض والأوركيد',
    nameEn: 'Royal White Lily & Orchid Crystal Vase',
    descriptionAr: 'فازة كريستال إيطالية ضخمة مرصعة بالورد الأبيض الطبيعي والأوركيد وسيقان الأوكالبتوس المعتبرة دلالة على النقاء والرفعة.',
    descriptionEn: 'Grand Italian crystal vase arranged with fresh Casablanca lilies, orchids, and aromatic eucalyptus stems.',
    price: 85.00,
    originalPrice: 95.00,
    category: 'bouquets',
    occasionId: 'thank-you',
    images: [FLOWER_1, FLOWER_2],
    inStock: true,
    stockQuantity: 10,
    tagsAr: ['فازات', 'زنبق أبيض', 'أوركيد', 'فخامة'],
    tagsEn: ['Vase', 'White Lilies', 'Orchids', 'Luxury'],
  },
  {
    id: 'pink-baby-hamper',
    nameAr: 'سلة استقبال المولود الملكية (وردي وسماوي)',
    nameEn: 'Royal Baby Welcome Hamper',
    descriptionAr: 'سلة خيزران مغطاة بالدانتيل تحتوي على باقة ورد بيبي جوري، شوكولاتة مواليد، ودبدوب فاخر مصنع يدويًا.',
    descriptionEn: 'Lace-embellished wicker hamper with baby roses, customized chocolates, and a handmade luxury plush bear.',
    price: 48.00,
    originalPrice: 55.00,
    category: 'baby',
    occasionId: 'baby',
    images: [FLOWER_2, CHOCOLATE_1],
    inStock: true,
    stockQuantity: 12,
    tagsAr: ['مواليد', 'سلة استقبال', 'وردي'],
    tagsEn: ['New Born', 'Baby Hamper', 'Soft Pink'],
  },
  {
    id: 'abaq-grand-heritage-set',
    nameAr: 'طقم عبق نزوى التراثي الملكي - الورد والعطر والذهب',
    nameEn: 'Abaq Nizwa Grand Heritage Luxury Set',
    descriptionAr: 'الهدية الأكثر فخامة لدى عبق نزوى. تشمل صندوق مخملي برغندي مطرز بالذهب، 40 وردة جورية، عطر عبق 100ml، وشوكولاتة مذهبة.',
    descriptionEn: 'The flagship luxury gift set: handcrafted burgundy velvet chest with 40 roses, 100ml perfume, and gold truffle chocolate box.',
    price: 135.00,
    originalPrice: 160.00,
    category: 'luxury-gifts',
    occasionId: 'wedding',
    images: [FLOWER_1, PERFUME_1, CHOCOLATE_1],
    isBestSeller: true,
    isFeatured: true,
    isNew: true,
    inStock: true,
    stockQuantity: 8,
    tagsAr: ['طقم ملكي', 'هدايا كبار الشخصيات', 'VIP'],
    tagsEn: ['Royal Set', 'VIP Gift', 'Heritage'],
  },
];

export const SEED_COUPONS = [
  {
    id: 'c-1',
    code: 'ABAQ10',
    discountPercent: 10,
    minOrder: 20,
    validUntil: '2026-12-31',
    active: true,
    usageCount: 0,
  },
  {
    id: 'c-2',
    code: 'NIZWA15',
    discountPercent: 15,
    maxDiscount: 15.00,
    minOrder: 40,
    validUntil: '2026-12-31',
    active: true,
    usageCount: 0,
  },
  {
    id: 'c-3',
    code: 'ROYAL20',
    discountPercent: 20,
    maxDiscount: 25.00,
    minOrder: 70,
    validUntil: '2026-12-31',
    active: true,
    usageCount: 0,
  },
];
